### ISSUE TITLE
Not compatible with Node 19+

### ISSUE THREAD

**Issue by Tiefseetauchner** [martinkadlec0/hc-tcg#100]
[Node 19+ removed support for --experimental-specifier-resolution=node](https://nodejs.org/en/blog/announcements/v19-release-announce/#custom-esm-resolution-adjustments)

I would (if not going to be fixed too soon) note it in the readme, add something like:

-------

This project does not yet support node v19+. Install node 18 or use [nvm](https://github.com/nvm-sh/nvm) to run:

```
hc-tcg $ nvm install 18
Downloading and installing node v18.14.2...
Downloading https://nodejs.org/dist/v18.14.2/node-v18.14.2-linux-x64.tar.xz...
####################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v18.14.2 (npm v9.5.0)
Creating default alias: default -> 18 (-> v18.14.2)
hc-tcg $ nvm exec 18 npm start
```

-------

I don't wanna meddle in your readme and make a PR, a look at my repos shows why I think. Hope this at least helps write the note

Also, I'm not really smart enough to understand node and the new --loader option, I'm just a C# dev wanting to write VSTO addons

Lena

**Comment by martinkadlec0** [comment]
Thanks for letting me know. Ideally we should also update package.json engines field.

**Comment by martinkadlec0** [comment]
Fixed https://github.com/martinkadlec0/hc-tcg/commit/248d47b579206ebb6e82e2c584f27735ff0b66b5
