### ISSUE TITLE
Clarify deck card count 

### ISSUE THREAD

**Issue by DatHypnoboi** [martinkadlec0/hc-tcg#105]
On the Deck Customization screen, if you have too few cards in your deck, it says "Deck must have at least 42 cards." which implies that the deck can have more than 42 cards, and as far as I know, it has to have exactly 42. Should probably just say something like "Deck must have 42 cards." or "Deck can not have less than 42 cards." if you want to keep the wording from too many cards

**Comment by martinkadlec0** [comment]
The game now shows total cards remaining.
