### ISSUE TITLE
When cloning tabs one player can be connected multiple times

### ISSUE THREAD

**Issue by martinkadlec0** [martinkadlec0/hc-tcg#11]
When player logs in we keep in session in session storage. When a tab is cloned/duplicated they keep the same session and so one player can be connected with multiple sockets. Right now only the latest opened tab will receive messages from server.

Goal:
- Improve server messaging logic to work with multiple sockets for one player.

**Comment by hglbrg** [comment]
This was unintentionally "fixed" (for me) with the CORS change some commits ago. Albeit that also did limit me from playing myself for testing purposes.

**Comment by martinkadlec0** [comment]
I don't see how cors could affect this, you are still connecting the same two domains.

**Comment by Sense101** [comment]
The server now handles matchmaking requests from the client much better, so even though you can have 2 duplicate tabs open as the same player, it won't actually affect anything anymore.
