### ISSUE TITLE
Prevent all card placing actions until player chooses active hermit after rare Jevin's special attack

### ISSUE THREAD

**Issue by CyanScales** [martinkadlec0/hc-tcg#113]
After rare Jevin's secondary attack, the opponent is forced to choose a new active hermit (assuming 2+ hermits on the board).  But currently the opponent player is still allowed to place item cards (and likely effect cards) _before_ choosing a new active hermit.

I've seen this lead to mistakes by the opponent, where they place more item (and likely effect) cards on the newly AFKed hermit.  But once they realize their mistake of not noticing that the hermit they just placed the card on is AFK, they can´t undo it.  A newly placed item card cannot be removed.

Since there currently isn't an obvious prompt for the opponent player to choose a new active hermit, _and_ they can play more item (and likely effect) cards on their newly AFKed hermit, it is easy for mistakes like this where the opponent continues to play assuming the newly AFKed hermit is still active.

**Comment by Sense101** [comment]
Outdated, this is how it works now in v0.6
