### ISSUE TITLE
Limitations in Minecraft limit the maximum unique cards per deck to 27.

### ISSUE THREAD

**Issue by James103** [martinkadlec0/hc-tcg#117]
In the official Hermitcraft server, the way the TCG system works is that players put their decks in shulker boxes before the match.
Shulker Boxes can only hold up to 27 different types of items; therefore, a deck with more than 27 different cards (not counting duplicates) wouldn't fit into a single shulker box and would therefore be truncated when used in a match.

I don't see any mention of this constraint being enforced in this version of TCG; therefore, it appears players may be able to build decks which would not fit in the official system as built in Minecraft.

Therefore, if a player build a deck with 28 or more unique cards,
* Expected behavior (if the switch for unique card limit is thrown): Error message "Deck may not have more than 27 different cards"
* Actual behavior: Deck is acceptable

**Comment by martinkadlec0** [comment]
While we don't have this specific limitation (as are not limited by shulker boxes), we have lot's of other limitations than don't exist on the HC server. Like max 12 rares/3URs. No UR duplicates etc. Given that I don't think this is something we need to add to the online version.
