### ISSUE TITLE
[Unimportant] Game keeps warning of unused moves on first turn

### ISSUE THREAD

**Issue by TypicallyThomas** [martinkadlec0/hc-tcg#118]
Stuff like swapping active Hermits and playing single use effects on turn 1. I find that reminder incredibly helpful on turn 2 but given there's no hermit to use my lava bucket on and since I put my active hermit on deliberately there's no point in reminding me of this stuff cause I can't use it. It's not important but it's annoying

**Comment by Tyrannicodin** [comment]
@Sense101 Pretty sure this was fixed
