### ISSUE TITLE
[NEEDS REPRO STEPS] Hypno's attack sometimes doesn't consume item cards.

### ISSUE THREAD

**Issue by martinkadlec0** [martinkadlec0/hc-tcg#12]
I've got multiple reports that Hypno's attack doesn't consume the selected item cards. This is okay when player selects to attack active  hermit, but it is reported that sometimes this happens even when attacking afk hermits. 

I haven't been able to reproduce this yet, so looking for reproduction steps.

**Comment by xeapnea** [comment]
one note to anyone looking to add to this, hypnos attack wont remove a card if the hermit chosen is the avtive hermit, this is intented, however it will still ask you to select a card, which for now: "[the devs] dont have mechanics to conditional disable the selection, so [they] just ask for it every time and then decide on server if we should use it or not"
