### ISSUE TITLE
Highlight end turn when there are no valid moves left

### ISSUE THREAD

**Issue by AS1624** [martinkadlec0/hc-tcg#121]
It is annoying when I or my opponent attacks, then has no legal moves left, but forgets to click "end turn", and just makes the game take longer. this would be a great quality of life feature, and would speed up games as well.

**Comment by Sense101** [comment]
I think a better option is to highlight the end turn button when there are no other moves left

**Comment by Sense101** [comment]
Implemented now in v0.6
