### ISSUE TITLE
Coin flip broken

### ISSUE THREAD

**Issue by TypicallyThomas** [martinkadlec0/hc-tcg#122]
Some players have figured out how to game the coin flips. I have just finished my 5th game where my opponent got 100% heads. Literally never a single tails. 30 heads, 0 tails

**Comment by Sense101** [comment]
The coin flips are random, but random can do that.

**Comment by TypicallyThomas** [comment]
I have played 10 more games where my opponent is getting heads only. It's definitely not properly random. I'm suspecting people are seeding the RNG before coin flips
