### ISSUE TITLE
Deck save/load confirmation

### ISSUE THREAD

**Issue by RadioArsenic** [martinkadlec0/hc-tcg#128]
Some kind of alert or something to let the user know that their deck saved or loaded, super simple and doesn't really change anything but helps with peace of mind, especially for users who have a lot of similar decks or first timers paranoid about whether their deck saved.

**Comment by Sense101** [comment]
This is actively being worked on

**Comment by RadioArsenic** [comment]
Ah sorry couldn't find an issue for it. Would you like me to close this one?

**Comment by Sense101** [comment]
This is fine till we actually implement it - it's helpful to have issues so we can keep track of things

**Comment by Sense101** [comment]
Implemented now on the beta branch
