### ISSUE TITLE
[Bug] Bed attached while sleeping doesn't restore health

### ISSUE THREAD

**Issue by janTasija** [martinkadlec0/hc-tcg#136]
Steps to reproduce:

1. Attach a bed to your active hermit
2. Get attacked by the opponent, who has no effect card attached
3. Use the Emerald effect card, which moves the bed to the opponent and frees your effect slot
4. Attach another bed to your hermit
5. Your hermit's health is not restored

It should be restored because the card description says it heals whenever it is applied, nothing about having to not be asleep.

I forgot to note if sleep duration resets and I haven't checked if the same happens if you've had your bed removed by the Curse of Vanishing effect card or rare Grian by your opponent, I'll update this if I have a chance to test it

**Comment by Sense101** [comment]
We fixed this a while back - which server is this on?

**Comment by janTasija** [comment]
hc-tcg.fly.dev, happened the same day i created the issue

**Comment by Sense101** [comment]
will look into this, thanks
