### ISSUE TITLE
[Bug?] Mending doesn't get discarded when used with Emerald

### ISSUE THREAD

**Issue by janTasija** [martinkadlec0/hc-tcg#137]
1. Your active hermit has Mending attached
2. Use Emerald (swap effect cards)
3. Mending moves to the opponent's active hermit

I think Mending should get discarded before swapping effect cards, because this way it can be used with Emerald indefinitely

**Comment by Sense101** [comment]
This is intended. Mending is only supposed to take effect after the single use effect card has been used, at which point you've already moved it over with emerald.
