### ISSUE TITLE
[Bug] Golden Axe against Sheep Stare interaction

### ISSUE THREAD

**Issue by JackSimpson2077** [martinkadlec0/hc-tcg#149]
When using a golden axe against a successful sheep stare, the effect of it ignoring effects is not carried over to the user. Instances: golden axe did not cut through diamond armor but still applied + 40 dmg, acting as a diamond sword would. golden axe did not cut through totem, but still applied the 40 dmg like the previous situation

**Comment by Sense101** [comment]
Fixed in the beta
