### ISSUE TITLE
Double item cards do not sort properly

### ISSUE THREAD

**Issue by Sense101** [martinkadlec0/hc-tcg#155]

**Comment by JoCodesThings** [comment]
What is the proper order? How do you feel about the following examples?
![Schermafdruk van 2023-06-14 17-24-53](https://github.com/martinkadlec0/hc-tcg/assets/39169351/f3042fa5-fa52-43af-b24b-deb5c319f25c)
![Schermafdruk van 2023-06-14 17-28-08](https://github.com/martinkadlec0/hc-tcg/assets/39169351/b328de07-49ff-497e-b791-2dacbcfccd26)

**Comment by JoCodesThings** [comment]
@Sense101 Could you provide some more info? I'd like to pick this one up if that's okay (as you can see I already have some potential solutions stashed)

**Comment by Sense101** [comment]
@JoCodesThings I tihnk example 1, but with the double items after the single ones, makes the most sense

**Comment by JoCodesThings** [comment]
> @JoCodesThings I tihnk example 1, but with the double items after the single ones, makes the most sense

Yeah, the intention of the original code seems to have been to sort the double item _before_ the single item, so I stuck to that initially. But I agree it makes more sense to have them the other way around, so that's what I did in my PR.
