### ISSUE TITLE
Make it more obvious when player has a card selected

### ISSUE THREAD

**Issue by martinkadlec0** [martinkadlec0/hc-tcg#2]
When you click on slots on the board there are two different behaviors depending on if you have a cars selected or not.

This can be a bit confusing, e.g. if you have a cards selected clicking on hermits will not open the attack modal/change active hermit but will try to place the card instead.

We should make it somehow more obvious the card is selected to avoid confusion.

**Comment by SoundanchorD** [comment]
What if the card just raises a bit up when selected

**Comment by martinkadlec0** [comment]
@SoundanchorD we already have the blue border. I was thinking to maybe have something floating around the cursor, or maybe just show a modal when you try to place card on already filled slot.

**Comment by sataylor7** [comment]
from a UI/UX/Design perspective the blue border doesn't really do anything.  
On the selected card we can use the  scale css var to make it a bit bigger (drawing focus), as well as change the border to be a better contrasting color, even adding some shadow to make it look as though it is glowing. 
On the board itself there can be a check to see if the space is already filled, and then show the modal as you mentioned. I haven't had a chance too look too deeply into the css yet
