### ISSUE TITLE
After a hermit is knocked out player can add a new hermit on board to make it active and attack with it on the same turn

### ISSUE THREAD

**Issue by martinkadlec0** [martinkadlec0/hc-tcg#21]
You should be allowed to activate and attack with a hermit that was already on the board but if you add a new one and make it active you shouldn't be able to attack on the same turn.

**Comment by xeapnea** [comment]
also if you add a hermit after one gets knocked out, the hermit you added is auto selected as the new active hermit (maybe this is a seperate bug?)
