### ISSUE TITLE
Prevent old clients from logging in

### ISSUE THREAD

**Issue by martinkadlec0** [martinkadlec0/hc-tcg#22]
We might run into issues with people having old client version open after an server update. We should add a version check on login and reload client browser if versions don't match.

**Comment by martinkadlec0** [comment]
https://hc-tcg.fly.dev/assets/index-ecaba6c0.js
the index of the bundled code has always a new hash for every version
perhaps we could just use that
and compare with the current hash in index.html

**Comment by Czompi** [comment]
Also we could send a connection packet with the client version (or the hash of the bundled code, you mentioned) to the server, and the server could refuse the connection if the packet version does not match the server version. It could also mitigate very old versions, so it is purely server-side (and maybe notify the player, that they need to refresh the page or just refresh it automatically).

**Comment by martinkadlec0** [comment]
Done https://github.com/martinkadlec0/hc-tcg/commit/0b955d6e330846f1f1de879a11dbb3ae76467dcb
