### ISSUE TITLE
[Unimportant] The typeface of π in TFC's =π attack is off

### ISSUE THREAD

**Issue by JoelleJS** [martinkadlec0/hc-tcg#273]
![Schermafdruk van 2023-06-18 12-05-45](https://github.com/martinkadlec0/hc-tcg/assets/39169351/f9c3f2d7-fe65-4c09-b3e1-b4660336f99f)

This probably requires editing the font files, so I'm not sure if it is feasible to fix this.

**Comment by Sense101** [comment]
Fixed next update
