### ISSUE TITLE
Clock on turn 1

### ISSUE THREAD

**Issue by FabianStammen** [martinkadlec0/hc-tcg#32]
When you are the starting player, playing clock on turn 1 does not work properly.
When played the confirmation dialog pops up and after picking yes, the dialog closes and reopens.
Repeatable until player picks no for an answer.

**Comment by martinkadlec0** [comment]
It's intended you shouldn't be able to use it on first turn.
We need better mechanics to tell player that is the case though. (Same things for all the other effects that can't be used at the moment).
