### ISSUE TITLE
Chat open as default

### ISSUE THREAD

**Issue by FabianStammen** [martinkadlec0/hc-tcg#33]
Many players don't seem to realize that there is a chat as it is closed by default and the button is rather small.
It could be open by default with the option to close or minimize.

Also remeber the state of the chat window from prevoius matches in a variable in memory. This way player do not have to reopen (or minimize if default is open ) chat every game.

**Comment by martinkadlec0** [comment]
The problem with having chat open by default are smaller screen where the chat cover left par of the board. I think the best thing to do here is to make the button more noticeable + like you said remember the opened state in long term storage.

**Comment by Tiefseetauchner** [comment]
I had the idea to make the chat appear as an overlay when closed, kind of like the Minecraft chat, not a frontend dev and probably the same issue with smaller screens tho, not something I can tackle (as no frontend dev)

**Comment by martinkadlec0** [comment]
Now the chat remembers closed/opened state.
