### ISSUE TITLE
Armor doesn't interact properly with non-hermit damage sources

### ISSUE THREAD

**Issue by RepublicofPixels** [martinkadlec0/hc-tcg#35]
When using TNT, or attacking someone with a Wolf (I haven't played against a Thorns book to test), and with lava/poison on their own with no attack (unsure if lava&poison are intentional), amor doesn't properly reduce the damage, instead letting the full damage through. This is unintentional behaviour for at least TNT, as the hermits have used that tactic, and the rest may or may not be intentional,  I can't source from the hermits.

**Comment by martinkadlec0** [comment]
Thanks for the report. I've been aware of this one but haven't create a bug for it yet so it is nice to keep track of it.

**Comment by martinkadlec0** [comment]
Should be fixed.
