### ISSUE TITLE
Game log showing actions taken

### ISSUE THREAD

**Issue by MCMan6482** [martinkadlec0/hc-tcg#36]
Feature request:
It would be great to have a log (either viewable during matches or post-match) that shows exactly what happened each turn. Especially for effects that affect the other player. ie:

Etho attacked Ren with move for 70hp-20hp(iron armor) Coin flip: tails.
Player X played Curse of Vanishing removing Netherite Armor.

**Comment by martinkadlec0** [comment]
Yeah, I was also thinking it would be nice to have something like that. Probably not something for near future, but hopefully later on we can add something like this.

**Comment by hglbrg** [comment]
I think a combined chat and log makes sense, similar to how the actual game (Minecraft) both has chat and events. 

The events are already being logged (the payload(s) contain what happened), so transcribing the object into readable information should be possible. Wish I had time to contribute code and not just ideas and speculation.

**Comment by martinkadlec0** [comment]
I guess it will depend on how busy the log is going to be, you also don't want to have 20 game messages between every actually message.

**Comment by hglbrg** [comment]
No they would have to be limited to reasonable actions, right now with the logging, it spams a lot. 

Essentials:
- [{turn}] {player} played {card} 
- [{turn}] {player} attacked {opponent}'s {opponent_active_hermit} using {active_hermit_skill} dealing {damage} damage. 
- Poison/Lava ticks (think that is pretty useful information)

Other actions to consider:
- Switching active hermit
- (Side)/ effects of cards
- Playing hermit cards (adding new hermits on board)
- Attaching items to hermits
- Card draws (completely unnecessary but including for completeness)

**Comment by hglbrg** [comment]
Also this should be its own issue, sorry, but on the topic I think it would be reasonable to have the console.log's hidden behind a hard DEV_MODE flag that one can toggle when testing. There have been cases...

**Comment by martinkadlec0** [comment]
Tbh, I fixed several bugs because people had access to the logs :D But yeah eventually of course they have to be hidden.

**Comment by Tyrannicodin** [comment]
@Sense101 This can be closed
