### ISSUE TITLE
Issue(?) with Rare Impulse Boomer Attack

### ISSUE THREAD

**Issue by MrBugFinderGuy** [martinkadlec0/hc-tcg#48]
[Note: This is not the same as issue #13]
Currently Impulse's boomer attack will not increase past +40 if the additional boomers are of the same name.
IE: If there is 1 impulse and 2 tangos on the field, the attack will do 110 damage.

It is possible that this is working as intended, but the Rare Impulse card text (printed below) does not suggest that.

> Boomer: Does an additional +40HP for every AFK boomer (BDubs, Tango) up to a maximum of +80HP damage.

If this is working as intended, I recommend changing the text to read:

>  Boomer: Does an additional +40HP for every AFK unique boomer (BDubs, Tango) up to a maximum of +80HP damage.

I understand though changing the text on the card to be different from the HermitCraft server is a debate to be had in it of itself, though.

**Comment by martinkadlec0** [comment]
This was a discussion for a while. I confirmed it with Beef and you are right, even duplicate Tango/Bdubs should work. However he also confirmed that other Impulse cards should NOT work. I have fix already on master branch. It will be  in next update.
