### ISSUE TITLE
[Enchantment] Get this into a Discord Activity as well

### ISSUE THREAD

**Issue by Miniontoby** [martinkadlec0/hc-tcg#480]
Hi,

Discord released the Embedded App SDK which allows you to create your own activity.

It would be cool if we can play this also from within a Discord voice channel.

I am willing to help out, but I haven't looked at the code yet, so maybe I personally would be unable to make it, but we will see.

- Miniontoby

**Comment by Sense101** [comment]
Hi. This is not an issue

**Comment by Miniontoby** [comment]
Where else do I need to post a feature request! Come on!

In normal github repositories you can just use issues for that type of things!

**Comment by Sense101** [comment]
Hey, sorry if that sounded a bit harsh. This isn't related to the game itself, it's more of a suggestion to expand the game to somewhere else, which I don't think belongs here.

**Comment by zunda-arrow** [comment]
This is a super creative idea and I love this! I'm not sure if this is something we would want to officially support, but feel free to ask on the discord if you have any questions on how to get started implementing this, and if it does work out maybe it can be official. I'm happy to see people tinker around with this project so don't be scared to ask for help!

(Please ignore the previous response, the project is run by me and @benji now)
