### ISSUE TITLE
Rare Scar can revive multiple times

### ISSUE THREAD

**Issue by LadyVaporeon99** [martinkadlec0/hc-tcg#63]
The card text says Scar can only be revived once but in a match I was in the same Scar card was revived 3 times via the deathloop attack all three times. (Y'all are doing great, keep up the good work)

**Comment by martinkadlec0** [comment]
Do you remember any details? Were any status effect (fire/poison) involved? Did they roll heads every single time when being revived?

**Comment by LadyVaporeon99** [comment]
It was poision, one time, and fire another time, think it worked after i
finished him off normally but i assumed it was just the coin flip landing
on tails.

**Comment by martinkadlec0** [comment]
Thanks for the info, it helped. It is fixed and should be out with next release.
