### ISSUE TITLE
Swapping to AFK is instantaneous, but should have a confirmation

### ISSUE THREAD

**Issue by christianhoward** [martinkadlec0/hc-tcg#64]
When a user clicks on an AFK hermit, the AFK hermit instantly becomes active. To avoid accidental clicks, there could be a user prompt that asks for confirmation before setting a hermit from AFK to active. This forces a user to be intentional about going AFK as opposed to accidentally going AFK and not being able to undo it.

**Comment by martinkadlec0** [comment]
Done.
