### ISSUE TITLE
Players have no idea if a user disconnects

### ISSUE THREAD

**Issue by christianhoward** [martinkadlec0/hc-tcg#65]
The game doesn't end if a user disconnects/closes the window. They are just stuck in the game until they leave as well. A notification could pop up when a user disconnects (assuming it uses web sockets to sync game state).

Steps to reproduce:
1.) open the game in 2 browsers with 2 different users (1 can be in incognito)
2.) create a private match and join in both browsers
3.) play out a few turns in the game from both sides
4.) close the browser for one user and look at the other browser to see no state change

**Comment by martinkadlec0** [comment]
Hey, we are aware of the issue, this is something on the TODO but there are just too many higher priority things at the moment.

However even now games should end if players closes their tab after a minute.

**Comment by martinkadlec0** [comment]
This should eb done now. When player disconnects their name becomes grey until they reconnect again.
