### ISSUE TITLE
Should be able to select new Hermit from hand as active Hermit after Hermit on board is knocked out

### ISSUE THREAD

**Issue by MidnightIce25** [martinkadlec0/hc-tcg#66]
![image](https://user-images.githubusercontent.com/126113935/220750581-9a6c549e-43cc-425b-bc4e-5fbb0556c454.png)

After the Hermit on the board is knocked out, if there is a Hermit in your hand, you should be able to choose that Hermit as the new active Hermit. Instead, if there is only one Hermit on the board and it is knocked out, you immediately lose. If there are more Hermits on the board, you must currently choose one of them as the active Hermit instead of being able to choose one from your hand.

**Comment by martinkadlec0** [comment]
Both are intended, its the same way on hermitcraft.
