### ISSUE TITLE
Hermit ability resolves before effect

### ISSUE THREAD

**Issue by TheIrishPizzaGuy** [martinkadlec0/hc-tcg#69]
Not sure if this is intended

Played a TNT on 10hp with a rare false (flip 40hp health restore)

instead of getting KO'd false went to 30hp

**Comment by RoyaLProg** [comment]
Not sure to understand, should :

+ False be KO'd no matter what

OR

+ If flipped success, False be at 20HP ?

**Comment by TheIrishPizzaGuy** [comment]
> Not sure to understand, should :
> 
> * False be KO'd no matter what
> 
> OR
> 
> * If the flipped coin is a success, False be at 30HP ?

I'm honestly not to sure. It caught me by surprise and seemed like a rare enough event to bring attention to. If TFC used branch mine I would expect that to still work on a self KO with TNT, but I expected false to be KO'd

**Comment by Sense101** [comment]
Outdated.
