### ISSUE TITLE
Make max turn time.

### ISSUE THREAD

**Issue by fazi3294** [martinkadlec0/hc-tcg#73]
There are players that do not do anything, just waiting for surrender.  I do not know why, for statistics i guess. Maybe after 90 sec they lose a point or something. Or allow AFK if the other player accepts, for some real situations that some one must step away for 5 minutes.

**Comment by MidnightIce25** [comment]
Timer is good but can we have a display for it instead of just timing out with no warning? Makes it a bit confusing when it just skips a turn all of a sudden.

**Comment by martinkadlec0** [comment]
There is a visible time, refresh your client :)
