### ISSUE TITLE
Using 'Clock' and defeating active hermit, does not require opponent to select new active hermit

### ISSUE THREAD

**Issue by hglbrg** [martinkadlec0/hc-tcg#75]
Reproduction
1. Use Clock on your turn, which skips opponents next turn. 
2. During your turn defeat opponents' active hermit.
3. End turn
4. Opponents' turn is skipped
5. Your turn again, but there is no active hermit to attack (effectively wasting that "bonus" turn in terms of damage done)

Expected result:
If Opponent is skipped AND has no active hermits, allow for activating one hermit, but block them from any other action

Actual result:
Opponent does not need to select a hermit, or is unable to really, so on your next turn there is no active hermit to attack.

**Comment by martinkadlec0** [comment]
fixed on hc-tcg
