### ISSUE TITLE
Please give Credits to VintageBeef

### ISSUE THREAD

**Issue by uriesk** [martinkadlec0/hc-tcg#85]
Just some disclaimer at the bottom of the entry page or something.
It just feels wrong to not have the creator of the game mentioned anywhere.

**Comment by martinkadlec0** [comment]
good point

**Comment by martinkadlec0** [comment]
Fixed by https://github.com/martinkadlec0/hc-tcg/commit/85eaea90af0a472219f91425bae125c0e8963776 until we have a proper credits page.
