### ISSUE TITLE
Does this project have permission to use the image assets?

### ISSUE THREAD

**Issue by John52869** [martinkadlec0/hc-tcg#91]
There many image files in this repo, many of them of the Hermits.

**Does this project have permission to use these image assets?**

I first thought of this when seeing how similar this project's hermit cards **look like the ones VintageBeef created in his series**.  But there is also the similarity of the other game cards between this project and the cards VintageBeef created (i.e. "item" and "effect" cards).

But the question of usage permissions also applies to all the other image assets.

**Comment by martinkadlec0** [comment]
Hey, we are in touch with the hermits, some of the assets are provided by Beef himself. Of course, this project is and always will be completely free, we don't plan to monetize it in any way which is part of the agreement.
