### ISSUE TITLE
Items not working without opponent active hermit

### ISSUE THREAD

**Issue by DatHypnoboi** [martinkadlec0/hc-tcg#93]
Items that target AFK hermits like bow are unable to be used when the opponent doesn't have an active hermit, such as when they are knocked out when a clock is played. Doesn't seem intentional, but might be in keeping with rules

**Comment by martinkadlec0** [comment]
It is a bug that there can be no active hermit on the second turn of the clock, once that is fixed this should hopefully be resolved.

**Comment by martinkadlec0** [comment]
Should be fixed now since on turn skip user now has to pick new active hermit.
