### ISSUE TITLE
Joe time skip

### ISSUE THREAD

**Issue by SebSemos** [martinkadlec0/hc-tcg#97]
I should have recorded my game for better analysis.

But I just played a game against joe special move time skip.
He got head, the he used a fortune book then got head again.
later on, I'm pretty sure he got head two time in a row
Then, he got head and used a clock

I don't know if the book and the clock should be nerfed after a time skip? But I'm pretty sure the "cannot be used consecutively" doesn't works fine for joe :D 

I might recorde my games from now on, not always simple to keep track of all the heads and effects. :p

**Comment by Sense101** [comment]
This is outdated
